GET http://localhost:3000/users
###
GET http://localhost:3000/users/1
###
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Testuser",
  "password": "hopefullyHashed"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Testuser",
  "password": "hopefullyHashed"
}
###
GET http://localhost:3000/transactions
###
GET http://localhost:3000/currencies
###
POST http://localhost:3000/currencies
Content-Type: application/json

{
  "code": "JPY",
  "symbol": "¥",
  "name": "Japanese Yen"
}
###
GET http://localhost:3000/categories
###
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Kleidung",
  "description": "Ausgaben für Kleidung"
}
###
GET http://localhost:3000/transactions/users/1
###
GET http://localhost:3000/transactions/4
###
POST http://localhost:3000/transactions
Content-Type: application/json

{
  "userId": "1",
  "categoryId": "3",
  "amount": "50.00",
  "transactionType": "Einnahme",
  "currency": "EUR",
  "description": "Taschengeld"
}
###
GET http://localhost:3000/preferences
###
GET http://localhost:3000/preferences/1
###
DELETE http://localhost:3000/transactions/4
###
PATCH  http://localhost:3000/preferences/1
Content-Type: application/json

{
  "preferred_currency": "USD",
  "saldo": 1500
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###

GET http://localhost:3000/api/bank/link
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ5MTgzMDU0LTI4OTgtNGM0Yy05ZDA0LTkyYmM1MzJmNzI1MyIsImlhdCI6MTc3MDgxNzQzNiwiZXhwIjoxNzcwODIxMDM2fQ.Nl2UKPqIzr9-9yKdXob8M5uEDECqlz0zrHLk3U0EqZs

###

GET http://localhost:3000/api/bank/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ5MTgzMDU0LTI4OTgtNGM0Yy05ZDA0LTkyYmM1MzJmNzI1MyIsImlhdCI6MTc3MDgxNzQzNiwiZXhwIjoxNzcwODIxMDM2fQ.Nl2UKPqIzr9-9yKdXob8M5uEDECqlz0zrHLk3U0EqZs

###

POST http://localhost:3000/api/bank/sync/{ACCOUNT_ID}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ5MTgzMDU0LTI4OTgtNGM0Yy05ZDA0LTkyYmM1MzJmNzI1MyIsImlhdCI6MTc3MDYyMTUyNiwiZXhwIjoxNzcwNjI1MTI2fQ.c8qKiU5XjJ-mJdpMlvTR_LK1ZEZLRwdpxV6OLl69mCA

###

GET http://localhost:3000/api/bank/transactions/{ACCOUNT_ID}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ5MTgzMDU0LTI4OTgtNGM0Yy05ZDA0LTkyYmM1MzJmNzI1MyIsImlhdCI6MTc3MDgxNzQzNiwiZXhwIjoxNzcwODIxMDM2fQ.Nl2UKPqIzr9-9yKdXob8M5uEDECqlz0zrHLk3U0EqZs
###